--VIEW 1.VOTER_PARTICIPATION_PERCENTAGE_IN_EACH_CONSTITUENCY %voters who participated in the election in their respective constituency. 

CREATE OR REPLACE VIEW VOTER_PARTICIPATION_CONSTITUENCY AS
SELECT TRUNC ( ((SUM(VOTES.VOTER_ID)/SUM(VOTER.VOTER_ID)*100))) AS PERCENTAGE_VOTERS, CONSTITUENCY.CONSTITUENCY_NAME
FROM VOTER left OUTER JOIN VOTES 
ON VOTER.VOTER_ID=VOTES.VOTER_ID
JOIN PEOPLE 
ON VOTER.U_ID= PEOPLE.U_ID
JOIN CONSTITUENCY
ON PEOPLE.CONSTITUENCY_ID= CONSTITUENCY.CONSTITUENCY_ID
GROUP BY CONSTITUENCY.CONSTITUENCY_NAME
ORDER BY PERCENTAGE_VOTERS DESC;


--VIEW 2. CANDITATE_PARTICIPATION_LIST_FOR_A_PARTICUPLAR_POSITION
CREATE OR REPLACE VIEW CANDIDATE_PARTICIPATION_POSITION AS
SELECT POSITION.POSITION_NAME,
PEOPLE.FIRST_NAME, PEOPLE.LAST_NAME
FROM POSITION JOIN CANDIDATE 
ON POSITION.CANDIDATE_ID= CANDIDATE.CANDIDATE_ID
JOIN PEOPLE ON
CANDIDATE.U_ID=PEOPLE.U_ID;

--VIEW 3. LIST OF ALL IN-ELGIBLE VOTERS.
CREATE OR REPLACE VIEW INELIGIBLE_VOTERS AS
SELECT VOTER.VOTER_ID,  PEOPLE.FIRST_NAME, PEOPLE.LAST_NAME, PEOPLE.AGE, PEOPLE.CONSTITUENCY_ID
FROM PEOPLE FULL OUTER JOIN VOTER
ON PEOPLE.U_ID= VOTER.U_ID
WHERE PEOPLE.AGE< 18 OR VOTER.EXPIRY_DATE<SYSDATE;

--VIEW 4. LIST OF ALL VOTERS WHO PARTICIPATED IN ELECTIONS.
CREATE OR REPLACE VIEW VOTERS_PARTICIPATION AS

SELECT VOTES.VOTER_ID, VOTER.U_ID, PEOPLE.FIRST_NAME, PEOPLE.LAST_NAME, CONSTITUENCY.CONSTITUENCY_NAME
FROM VOTES
JOIN VOTER
ON VOTES.VOTER_ID=VOTER.VOTER_ID
JOIN PEOPLE
ON  VOTER.U_ID=PEOPLE.U_ID
JOIN CONSTITUENCY
ON PEOPLE.CONSTITUENCY_ID= CONSTITUENCY.CONSTITUENCY_ID;

--VIEW 5. COUNT OF CANDIDATES PARTICIPATING IN ELECTIONS PER PARTY
CREATE OR REPLACE VIEW CANDIDATE_PARTICIPATION_PARTY AS
SELECT CANDIDATE.PARTY_ID,PARTY.PARTY_NAME, COUNT(CANDIDATE.PARTY_ID) AS COUNT_OF_CANDIDATES from CANDIDATE 
JOIN PARTY
ON CANDIDATE.PARTY_ID= PARTY.PARTY_ID
GROUP BY CANDIDATE.PARTY_ID, PARTY.PARTY_NAME;

--VIEW 6. SELECT CANDIDATES WHO DID NOT CHANGE ANY PARTY
CREATE OR REPLACE VIEW CANDIDATE_NOCHANGE_PARTY AS
SELECT PEOPLE.FIRST_NAME, PEOPLE.LAST_NAME,CANDIDATE.PREVIOUS_PARTY FROM CANDIDATE 
JOIN PEOPLE
ON CANDIDATE.U_ID= PEOPLE.U_ID
WHERE CANDIDATE.PREVIOUS_PARTY='NONE';


--VIEW 7. COUNT OF TOTAL PEOPLE IN EACH CONSTITUENCY PER STATE
CREATE OR REPLACE VIEW TOTAL_PEOPLE_CONSTITUENCY_STATE AS
SELECT COUNT(PEOPLE.U_ID) AS TOTAL_PEOPLE, CONSTITUENCY.CONSTITUENCY_NAME, STATE.STATE_NAME
FROM PEOPLE 
JOIN CONSTITUENCY
ON PEOPLE.CONSTITUENCY_ID= CONSTITUENCY.CONSTITUENCY_ID
JOIN STATE
ON CONSTITUENCY.STATE_ID=STATE.STATE_ID
GROUP BY CONSTITUENCY.CONSTITUENCY_NAME ,STATE.STATE_NAME;


--VIEW 8. CANDIDATES WITH 10 OR MORE THAN 10 YEARS OF POLITICAL EXPERIENCE.
CREATE OR REPLACE VIEW CANDIDATE_TENPLUS_EXP AS
SELECT PEOPLE.FIRST_NAME,PEOPLE.LAST_NAME,CANDIDATE.EXP_YEARS
FROM PEOPLE 
JOIN CANDIDATE
ON PEOPLE.U_ID=CANDIDATE.U_ID
WHERE CANDIDATE.EXP_YEARS>=10;


--VIEW 9. PERCENTAGE OF MALE AND FEMALES IN EACH CONSTITUENCY AND STATE
CREATE OR REPLACE VIEW MALE_FEMALE_PERCENTAGE AS
SELECT ROUND(((SELECT COUNT(U_ID)FROM PEOPLE WHERE GENDER='F')/(SELECT COUNT(U_ID)FROM PEOPLE)*100),3)AS PERCENTAGE_FEMALES,
ROUND(((SELECT COUNT(U_ID)FROM PEOPLE WHERE GENDER='M')/(SELECT COUNT(U_ID)FROM PEOPLE)*100),3)AS PERCENTAGE_MALES, 
CONSTITUENCY.CONSTITUENCY_NAME, STATE.STATE_NAME
FROM PEOPLE 
JOIN CONSTITUENCY
ON PEOPLE.CONSTITUENCY_ID= CONSTITUENCY.CONSTITUENCY_ID
JOIN STATE
ON CONSTITUENCY.STATE_ID= STATE.STATE_ID
GROUP BY CONSTITUENCY.CONSTITUENCY_NAME, STATE.STATE_NAME;











